version: 2.1
#test
orbs:
  docker: circleci/docker@1.5.0
#hehehe
parameters:
  app1:
    type: boolean
    default: false

jobs:
  app1-job:
    docker:
      # next-gen ubuntu image with java 11.0.10
      - image: cimg/base:stable
    resource_class: small
    steps:
      - checkout
      - run:
          name: "Say hello"
          command: "echo app1 test1!"

workflows:
  app1:
    jobs:
      - app1-job
