version: 2.1
setup: true
orbs:
  path-filtering: circleci/path-filtering@0.1.3
workflows:
  setup:
    jobs:
      - path-filtering/filter:
          base-revision: circleci-project-setup
          mapping: |
            apps/app1/.* app1 true
          config-path: .circleci/workflows.yml



